### ISSUE TITLE
Recurring Error: Timeout fetching flo

### ISSUE THREAD

**Issue by xAcrosonicx** [rsnodgrass/hass-flo-water#16]
Hello,

I am receiving the following errors in my logs every hour or so, and it has been going on for months even after reboots, host reboots, reconfiguration, and removal and readding of the Flo integration:

> Logger: homeassistant.components.flo
> Source: helpers/update_coordinator.py:235
> 
> First occurred: 10:06:16 AM (4 occurrences)
> Last logged: 2:06:19 PM
> 
> Timeout fetching flo-ac8318a1-9838-4a2f-adf5-5ea53e1c43b2 data

-----------------------------------------------

> Logger: homeassistant.components.flo
> Source: helpers/aiohttp_client.py:72
> Integration: Flo (documentation, issues)
> First occurred: 1:05:42 PM (1 occurrences)
> Last logged: 1:05:42 PM
> 
> Unexpected error fetching flo-ac8318a1-9838-4a2f-adf5-5ea53e1c43b2 data: unexpected character: line 1 column 1 (char 0)
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 293, in _async_refresh
>     self.data = await self._async_update_data()
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/flo/device.py", line 43, in _async_update_data
>     await self.send_presence_ping()
>   File "/usr/src/homeassistant/homeassistant/components/flo/device.py", line 192, in send_presence_ping
>     await self.api_client.presence.ping()
>   File "/usr/local/lib/python3.11/site-packages/aioflo/presence.py", line 16, in ping
>     return await self._request("post", f"{API_V2_BASE}/presence/me")
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/aioflo/api.py", line 94, in _request
>     data: dict = await resp.json(content_type=None)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/aiohttp_client.py", line 72, in json
>     return await super().json(*args, loads=loads, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1120, in json
>     return loads(stripped.decode(encoding))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> orjson.JSONDecodeError: unexpected character: line 1 column 1 (char 0)

Here is information for my HA instance:

Home Assistant 2023.9.0
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230906.1 - latest
Flo info: flo_device_100_v2
by Flo by Moen
Firmware: 7.1.1-artifact-v2

**Comment by xAcrosonicx** [comment]
Hi @rsnodgrass - can you please look into this?

Thank you!
