### ISSUE TITLE
Update for switch.flo_water_valve fails

### ISSUE THREAD

**Issue by zaped212** [rsnodgrass/hass-flo-water#2]
Running master ( installed via HACS ) I am starting to see the following error.
The error repeats in the log every 30 seconds.

2020-01-23 08:50:33 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.flo_water_valve fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/flo/switch.py", line 84, in update
    data = self._flo.device(self._device_id)
  File "/usr/local/lib/python3.7/site-packages/pyflowater/__init__.py", line 185, in device
    data = self.query(url, method=METHOD_GET)
  File "/usr/local/lib/python3.7/site-packages/pyflowater/__init__.py", line 109, in query
    self.login()
TypeError: login() missing 1 required positional argument: 'password'

( Ill be happy to format this, but I cant find the appropriate items )

**Comment by rsnodgrass** [comment]
FYI, master is beta and not guaranteed to work; please use released versions.  I bumped the dependency to the latest pyflowater, so it should be working now.

**Comment by zaped212** [comment]
Yeah, I went to master since I was on 2.0.2 but was having difficulties with the stats not being updated ( was stale by 4 hours ). Since I saw there were improvements on master I went ahead and switched over and that seemed to get things working, until I hit that issue.

I went ahead and switched over to 2.0.3 now and will run that way.

I will leave it up to you if you would like to close out this ticket or not.
