### ISSUE TITLE
Update for switch.flo_water_valve fails on 2.0.3

### ISSUE THREAD

**Issue by zaped212** [rsnodgrass/hass-flo-water#3]
Added flo into my configuration on 2020-01-21T23:16:49-06:00 then at Sat Jan 25 2020 20:29:45 GMT-0600 the following log appears. Before then it seemed to be working though updates to pressure and flo rate would be delayed by 10s of minutes
`
Update for switch.flo_water_valve fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 461, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/flo/switch.py", line 84, in update
    data = self._flo.device(self._device_id)
  File "/usr/local/lib/python3.7/site-packages/pyflowater/__init__.py", line 184, in device
    data = self.query(url, method=METHOD_GET)
  File "/usr/local/lib/python3.7/site-packages/pyflowater/__init__.py", line 108, in query
    self.login()
  File "/usr/local/lib/python3.7/site-packages/pyflowater/__init__.py", line 41, in login
    self.login_with_password(password)
NameError: name 'password' is not defined

`

**Comment by rsnodgrass** [comment]
* 2.0.4 imports changes in pyflowater for re-authentication after login has expired
* I still have not had time to look into the 10 minute delay in pressure and Flo rates (Flo cloud service may cache the values for some period of time?)
