### ISSUE TITLE
Telemetry not updating frequently

### ISSUE THREAD

**Issue by jaossey50** [rsnodgrass/hass-flo-water#8]
On my integrations, through HACS, sensor.flo_water_consumption updates every few minutes, while items under telemetry (sensor.flo_water_pressure, sensor.flo_water_flow_rate, etc) far less frequently. 

What can I do to get better live data?

**Comment by rsnodgrass** [comment]
By default this integration updates every 60 seconds from Flo's web service. Either Flo service is not receiving updates from your sensor, or they are returning cached results.

You can update to latest version 2.0.10 to get more debugging output of what Flo is returning. Add to your logger: configuration.yaml entry to log all the flo integrations:



logger:
  logs:
    pyflowater: debug
    custom_components.flo: debug
    custom_components.flo.sensor: debug
    custom_components.flo.switch: debug

**Comment by mike240se** [comment]
is it possible flo changed something?  Mine is not really working at all.  Flo rate is always 0 (and randomly will go up to 1.x and then stay at that for a couple days and then go back to 0 for several days).  temp and pressure also dont change.

it seems the only thing working correctly is gallons used.  is it possible flo disabled most of the v1 api?  i saw some errors in the HA logs as well, going to go hunt for them and report back.

**Comment by jaossey50** [comment]
+1

**Comment by rsnodgrass** [comment]
Possibly.  The data being returned is correctly being process and displayed
in HA...but sometimes I get bad data back...and it matches what I see in
the Flo app.

If you click on the Flo Water Consumption, you can see ALL the data that
they return for your device.

What I *do* see, is that it appears that mine is not being updated
properly.  I'll look into why update() is not being called on the Flo
switch (which then updates all the other sensors).   We should see INFO
logs periodically that show:

"Updated latest Flo system mode info {valve} for {self._device_id}

**Comment by rsnodgrass** [comment]
I possibly found an issue related to Flo polling updates, testing on master
now.

**Comment by rsnodgrass** [comment]
I also noted in the response from Flo is that they mark the temperature
sensors as "broken":

componentHealth
  temp:
     health:
    broken updated: '2020-03-16T17:35:03.127887261Z'
  psi:
    health: ok
    updated: '2020-03-16T17:35:03.127886867Z'

And, I also see that Flo REMOVED the temperature from their cloud based
interface to our Flo devices.  So I think they might be deprecating
temperature.

**Comment by mike240se** [comment]
I'm still seeing a lot of errors with polling Flo:

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/flo/sensor.py", line 271, in update
    curr = self.readConsumption(start, now, '1h')
  File "/config/custom_components/flo/sensor.py", line 240, in readConsumption
    interval)
  File "/usr/local/lib/python3.7/site-packages/pyflowater/__init__.py", line 251, in consumption
    return self.query(url, method=METHOD_GET, extra_params=params)
  File "/usr/local/lib/python3.7/site-packages/pyflowater/__init__.py", line 130, in query
    request = self._session.get(url, headers=headers, params=extra_params)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2020-06-24 00:30:02 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.flo_water_consumption fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/flo/sensor.py", line 278, in update
    self.update_state(state)
AttributeError: 'FloConsumptionSensor' object has no attribute 'update_state'
2020-06-24 00:31:03 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.flo_water_consumption fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/flo/sensor.py", line 278, in update
    self.update_state(state)
AttributeError: 'FloConsumptionSensor' object has no attribute 'update_state'
2020-06-24 00:32:04 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.flo_water_consumption fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/flo/sensor.py", line 278, in update
    self.update_state(state)
AttributeError: 'FloConsumptionSensor' object has no attribute 'update_state'
2020-06-24 00:33:05 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.flo_water_consumption fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/flo/sensor.py", line 278, in update
    self.update_state(state)
AttributeError: 'FloConsumptionSensor' object has no attribute 'update_state'
2020-06-24 00:34:06 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.flo_water_consumption fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/flo/sensor.py", line 278, in update
    self.update_state(state)
AttributeError: 'FloConsumptionSensor' object has no attribute 'update_state'
2020-06-24 00:35:07 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.flo_water_consumption fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/flo/sensor.py", line 278, in update
    self.update_state(state)
AttributeError: 'FloConsumptionSensor' object has no attribute 'update_state'

**Comment by rsnodgrass** [comment]
Please update to the latest version, there was one file missing in the last
release.

**Comment by mike240se** [comment]
THanks I updated and restarted Ha but still seeing this:

requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2020-06-24 03:41:59 ERROR (MainThread) [homeassistant.helpers.entity] Update for switch.flo_water_valve fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/flo/switch.py", line 103, in update
    data = self._flo.device(self._device_id)
  File "/usr/local/lib/python3.7/site-packages/pyflowater/__init__.py", line 185, in device
    data = self.query(url, method=METHOD_GET)
  File "/usr/local/lib/python3.7/site-packages/pyflowater/__init__.py", line 130, in query
    request = self._session.get(url, headers=headers, params=extra_params)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by rsnodgrass** [comment]
From the error like Flo may have disabled another feature/API as they continue to evolve their product.
  

  
When I get some time I’ll see what is going on with switches.   
  

  
This will always be a bit of a cat and mouse game since Flo doesn’t have an officially supported API and as we’ve seen they will remove/change features without warning.   
  

  
  
  

  
  
>

**Comment by mike240se** [comment]
now am getting errors for consumption too, adding this incase its helpful:

2020-06-25 16:37:04 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.flo_water_consumption fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 279, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/flo/sensor.py", line 271, in update
    curr = self.readConsumption(start, now, '1h')
  File "/config/custom_components/flo/sensor.py", line 240, in readConsumption
    interval)
  File "/usr/local/lib/python3.7/site-packages/pyflowater/__init__.py", line 251, in consumption
    return self.query(url, method=METHOD_GET, extra_params=params)
  File "/usr/local/lib/python3.7/site-packages/pyflowater/__init__.py", line 130, in query
    request = self._session.get(url, headers=headers, params=extra_params)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

**Comment by mike240se** [comment]
could it be we are updating too often and triggering a black listing?

**Comment by rsnodgrass** [comment]
Possibly...everyone wants their data refreshed regularly though in HA, so it is a tough balance.    
  

  
In reality, other than flow rate, for mose use cases probably doesn’t need to update more than once every 15 or 30 minutes.   
  

  
  
  

  
  
>
